# === Edit me ===
engines: [duckdb, sqlite]

repeat_pilot: 3
sample_count: 10
std_repeat: 5
cwd : .

engine_paths:
  duckdb: duckdb
  sqlite: /Users/xiejiangzhao/sqlite3/bin/sqlite3

datasets:
  - name: vs14
    duckdb_db: ./db_vs14/vs14_data.duckdb
    sqlite_db: ./db_vs14/vs14_data.sqlite
    chdb_db_dir: ./db_vs14/vs14_data_chdb

query_groups:
  - id: Q1
    duckdb_sql: queries/Q1/Q1_duckdb.sql
    sqlite_sql: queries/Q1/Q1_sqlite.sql
    chdb_sql:   queries/Q1/Q1_clickhouse.sql
