# === Edit me ===
engines: [duckdb, sqlite]

repeat_pilot: 3
sample_count: 10
std_repeat: 5
output_cwd: ./results

engine_paths:
  duckdb: duckdb
  sqlite: /Users/xiejiangzhao/sqlite3/bin/sqlite3

datasets:
  - name: vs14
    duckdb_db: ./db_vs14/vs14_data.duckdb
    sqlite_db: ./db_vs14/vs14_data.sqlite
    chdb_db_dir: ./db_vs14/vs14_data_chdb

query_groups:
  - id: Q2
    duckdb_sql: /Users/xiejiangzhao/PycharmProject/dataset_analytics/benchmark/queries/anomaly/Q2_duckdb.sql
    sqlite_sql: /Users/xiejiangzhao/PycharmProject/dataset_analytics/benchmark/queries/anomaly/Q2_sqlite.sql

  - id: Q3
    duckdb_sql: /Users/xiejiangzhao/PycharmProject/dataset_analytics/benchmark/queries/anomaly/Q3_duckdb.sql
    sqlite_sql: /Users/xiejiangzhao/PycharmProject/dataset_analytics/benchmark/queries/anomaly/Q3_sqlite.sql

compare_pairs:
  - [ Q2, duckdb ]
  - [ Q2, sqlite ]