name: Build SQLite snapshot

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-sqlite.yml

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Point this to a ZIP snapshot (e.g. https://sqlite.org/2025/sqlite-src-3500400.zip)
      SNAP_URL: https://sqlite.org/2025/sqlite-src-3500400.zip
      PREFIX: /usr/local
      CFLAGS: -O2 -DSQLITE_ENABLE_STMT_SCANSTATUS

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config unzip

      - name: Download and extract ZIP
        shell: bash
        run: |
          set -euo pipefail
          curl -L "$SNAP_URL" -o sqlite.zip
          unzip -q sqlite.zip
          # The first path component in the ZIP is the snapshot root directory
          ROOT_DIR=$(unzip -Z1 sqlite.zip | head -1 | cut -d/ -f1)
          echo "ROOT_DIR=$ROOT_DIR" >> "$GITHUB_ENV"
          echo "Snapshot root: $ROOT_DIR"
          test -d "$ROOT_DIR"

      - name: Configure
        working-directory: ${{ env.ROOT_DIR }}
        run: |
          set -euxo pipefail
          ./configure --prefix="${PREFIX}" --enable-shared CFLAGS="${CFLAGS}"

      - name: Build
        working-directory: ${{ env.ROOT_DIR }}
        run: make -j"$(nproc)"

      - name: Stage install (DESTDIR)
        working-directory: ${{ env.ROOT_DIR }}
        run: |
          set -euxo pipefail
          STAGE="${{ github.workspace }}/stage"
          make install DESTDIR="$STAGE"
          echo "STAGE=$STAGE" >> "$GITHUB_ENV"
          find "${STAGE}${PREFIX}" -maxdepth 2 -type d | sort

      - name: Collect install outputs
        run: |
          set -euxo pipefail
          OUTROOT="${{ github.workspace }}/sqlite-built"
          mkdir -p "$OUTROOT"
          SRCROOT="${STAGE}${PREFIX}"
          for d in bin lib include; do
            if [ -d "${SRCROOT}/${d}" ]; then
              mkdir -p "${OUTROOT}/${d}"
              cp -a "${SRCROOT}/${d}/." "${OUTROOT}/${d}/"
            fi
          done
          if [ -d "${SRCROOT}/lib/pkgconfig" ]; then
            mkdir -p "${OUTROOT}/pkgconfig"
            cp -a "${SRCROOT}/lib/pkgconfig/." "${OUTROOT}/pkgconfig/"
          fi
          echo "OUTROOT=$OUTROOT" >> "$GITHUB_ENV"
          find "$OUTROOT" -maxdepth 2 -type f | sort

      - name: Create build tarball
        run: |
          set -euxo pipefail
          ARCH="$(uname -m)"
          ROOT_BASENAME="$(basename "${ROOT_DIR}")"
          BUILD_TGZ="sqlite-build-${ROOT_BASENAME}-ubuntu-${ARCH}.tar.gz"
          tar -C "${OUTROOT}" -czf "${BUILD_TGZ}" .
          echo "BUILD_TGZ=$BUILD_TGZ" >> "$GITHUB_ENV"
          echo "Created: ${BUILD_TGZ}"
          tar -tzf "${BUILD_TGZ}" | head -n 20

      - name: Create source tarball
        run: |
          set -euxo pipefail
          SRC_TGZ="sqlite-source-${ROOT_DIR}.tar.gz"
          tar -czf "${SRC_TGZ}" "${ROOT_DIR}"
          echo "SRC_TGZ=$SRC_TGZ" >> "$GITHUB_ENV"
          echo "Created: ${SRC_TGZ}"

      - name: Verify compile options
        run: |
          set -euxo pipefail
          BIN="${STAGE}${PREFIX}/bin/sqlite3"
          "$BIN" "PRAGMA compile_options;" | grep -i STMT_SCANSTATUS
          "$BIN" --version

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_TGZ }}
          path: ${{ env.BUILD_TGZ }}
          if-no-files-found: error

      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SRC_TGZ }}
          path: ${{ env.SRC_TGZ }}
          if-no-files-found: error